# Generated by Django 5.2 on 2025-10-06 10:39

import The_App_Code.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('category', models.CharField(choices=[('budget', 'Budgeting'), ('remittance', 'Smart Remittances'), ('business', 'Small Business'), ('safety', 'Safety & Fraud')], default='budget', max_length=24)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('toolkit', 'Toolkit'), ('video', 'Video')], default='article', max_length=16)),
                ('call_to_action', models.CharField(default='Read Lesson', max_length=40)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('badge_text', models.CharField(blank=True, max_length=20)),
                ('reward', models.CharField(blank=True, max_length=120)),
                ('cta_label', models.CharField(default='View details', max_length=40)),
                ('cta_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_active', '-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=60)),
                ('quantity', models.PositiveIntegerField()),
                ('frequency', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='one_time', max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('behind', 'Behind'), ('ahead', 'Ahead')], default='on_track', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=6)),
                ('kind', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='outgoing', max_length=8)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('membership_level', models.CharField(default='Standard', max_length=32)),
                ('preferred_currency', models.CharField(default='USD', max_length=6)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('language', models.CharField(default='English', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=80)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month', models.DateField(default=The_App_Code.models.first_day_of_current_month)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'category'],
                'unique_together': {('user', 'category', 'month')},
            },
        ),
    ]
